### PR TITLE
Fix uploading multiple output packages (fixes #1)

### LINKED ISSUE #1: Only main tarball uploaded
Only the `openmotif` tarball is uploaded by `upload_or_check_non_existence.py`.

see conda-forge/conda-forge-build-setup-feedstock#68

The build system only defaults to the script from `build-setup`. Adding a custom script to `recipe/` may work to fix this w/o touching the main upload script.

### PR DESCRIPTION
**Pull request by epruesse**

### CODE REVIEW

**Comment by jakirkham** [comment]
FWIW adding the `upload_or_check_non_existence.py` script and simply re-rendering will have the same effect.

**Comment by epruesse** [comment]
That's what I did. Just took me a bit to dig through the scripts to realize that I could "overwrite" it for this recipe.

**Comment by jakirkham** [comment]
Ah ok. Cool.

I'm use to seeing the `MNT: Re-rendered with conda-smithy X.X.X` commit messages. So wasn't sure.

Yeah believe it or not that is intended to be a feature for all feedstocks should it be needed. Though, in practice, only `conda-forge-build-setup` uses them. Though it could come in handy if the build setup needs to get tweaked in a hurry. Probably should be documented. 😅

**Comment by epruesse** [comment]
I think documenting in the source is fine. If you are going to mess with the build process, you need to read that anyway. My issue was mainly figuring out where it came from because it's installed without the `.py`. Perhaps it could just log itself. E.g. `no local upload_or_check_existance found; using default from conda-forge-build-setup-feedstock.`

**Comment by epruesse** [comment]
It's good to have the option to override locally though. If only as a path for testing. I wouldn't claim it works if it hadn't here.

**Pull request merged**
