### PR TITLE
Trying to rerender for latest version of icu

### PR DESCRIPTION
**Pull request by piyushrpt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

libXm.so seems to be pinned to libicu18n.so.58 whereas the latest version is 64.2 . Trying to rerender to allowing building of other packages that depend on openmotif.

### CODE REVIEW

**Comment by piyushrpt** [comment]
@conda-forge-admin, please rerender

**Comment by piyushrpt** [comment]
This should hopefully help fix linux errors here: 
https://github.com/conda-forge/isce2-feedstock/pull/11

**Comment by piyushrpt** [comment]
@epruesse @ocefpaf Would it be possible to take a look at this PR and suggest changes? Hoping that updating this would let us update isce2-feedstock to using GDAL 3

**Comment by ocefpaf** [comment]
Version `2.3.8` was never built or removed for some reason. It is not in the channel. Merging this is nice b/c the re-render will help and the new version will be available, but I'm not sure this will help you with `icu` version. `openmotif` does not build against `icu`, does it?

**Pull request merged**
